################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
    - title: Introduction
      link:
      open: true
      sections:
        - title: Contact US
          link: docs/introduction/contact-us.md

- sections:
    - title: Getting Started
      link: docs/Tutorial.md
      open: true

- sections:
    - title: API Reference
      link:
      open: true
      sections:
        - title: Cloud POI 
          sections:
            - title: Login
              link: docs/APIs/UAM/UAM.md
            - title: PaymentAPI
              link: docs/APIs/PaymentAPI/ProcessAmount.md
        - title: Commerce Connect
          sections:
            - title: GetToken
              link: docs/APIs/CommerceConnect/GetToken.md
            - title: Decrypt Merchant Response
              link: docs/APIs/CommerceConnect/DecryptMerchantResponse.md
            - title: GET HMAC
              link: docs/APIs/CommerceConnect/GetHMAC.md
            - title: Get Txn Inquiry Detail
              link: docs/APIs/CommerceConnect/GetTxnInquiryDetail.md
            - title: Refund Txn Inquiry Detail
              link: docs/APIs/CommerceConnect/RefundTxnInquiryDetail.md
            - title: Encrypt Data Using AES
              link: docs/APIs/CommerceConnect/EncryptDataUsingAES.md
        - title: SameDay Boarding
          sections:
            - title: Login
              link: docs/APIs/Boarding/Login.md
            - title: Packageby ID
              link: docs/APIs/Boarding/PackagebyID.md
            - title: Package info
              link: docs/APIs/Boarding/Packageinfo.md
            - title: RefId Inquiry
              link: docs/APIs/Boarding/RefIdInquiry.md
            - title: get Application URN
              link: docs/APIs/Boarding/getApplicationURN.md
            - title: CREATE
              link: docs/APIs/Boarding/CREATE.md
            - title: Submit Application
              link: docs/APIs/Boarding/SubmitApplication.md
            - title: Additional Tid
              link: docs/APIs/Boarding/AdditionalTid.md
            - title:  Additional Mid
              link: docs/APIs/Boarding/AdditionalMid.md
            - title: add Location
              link: docs/APIs/Boarding/addLocation.md
            - title:  Upload merchant document
              link: docs/APIs/Boarding/UploadMerchantDocument.md
            - title: Get Document Matrix
              link: docs/APIs/Boarding/GetDocumentMatrix.md
        - title: Extenal Boarding
          sections:
            - title: Login
              link: docs/APIs/ExternalBoarding/Login.md
            - title: Submit Application
              link: docs/APIs/ExternalBoarding/SubmitApplication.md
            - title: Ref For Additional MID
              link: docs/APIs/ExternalBoarding/RefForAdditionalMID.md
            - title: CreateApplication
              link: docs/APIs/ExternalBoarding/CreateApplication.md
            - title: Get App Status
              link: docs/APIs/ExternalBoarding/GetAppStatus.md
            - title: Get Package List
              link: docs/APIs/ExternalBoarding/GetPackageList.md
            


