################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: AcceptanceSolutionsAPAC
  productionDescription: Retail is all about selling goods and services to the end-consumer - it's everywhere and is a vital part of our everyday life. And with the availability of mobile and internet connectivity, the concept of retailing has become increasingly popular. All these developments have led to the rapid expansion of the retail business domain.In today’s digital transaction expansion all end-consumers prefer to use credit/debit card at most available places to pay the bills.Most of the retailers has a central system to manage the stock and billing process. But the digital payments transactions are initiated separately on the POS devices with cashiers’ manual interventions, which makes it time consuming and lead to erroneous billing as the amounts are input manually.Fiserv Cloud POI is API (application programming interface) based integration which facilitate to connect with retailer’s central or any standalone systems to automate the entire billing to payments transactions.
  whoIsItFor: Fiserv Cloud POI is API (application programming interface) based integration which facilitate to connect with retailer's central or any standalone systems to automate the entire billing to payments transactions..
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: AcceptanceSolutionsAPAC™
featuredFeatures:
  - title: PaymentAPI
    description: This API is  based integration which facilitate to connect with retailer's central or any standalone systems to automate the entire billing to payments transactions..
    tags: ["UAM", "PaymentAPI"]
    bullets: ["Login", "PaymentAPI"]  
    relatedDocs:
      - relatedDoc: 
        title: Login
        description: Get Token.
        link: ./docs/UAM.md
      - relatedDoc: 
        title: Payment API
        description: Non OPi Processing Amount
        link: ./docs/PaymentAPI.md
    relatedAPIs:
      - relatedAPI: 
        title: Login
        description: This service is used to get the token.
        type: "post"        
        path: "/boardinggateway/boarding/auth/signin"
      - relatedAPI: 
        title: Payment API
        description: This API is  based integration which facilitate to connect with retailer's central or any standalone systems to automate the entire billing to payments transactions..
        type: "post"        
        path: "/boardinggateway/cloudpoi/PosPush/nonOpiProcessAmount"
 
