openapi: 3.0.2
info:
  title: Merchant On Boarding
  version: 1.0v
  description: ' The partner API '
servers:
- url: https://www.uat.fdmerchantservices.com
  description: UAT URL
security:
- BasicAuth: []
- ApiKeyAuth: []
tags:
- name: Boarding
  description: REST API for Boarding
paths:
  /Externalboarding/partner/login:
    get:
      tags:
      - Boarding
      summary: User Login
      description: User Login
      operationId: getAuthJWTToken
      x-group-name:  Boarding
      x-proxy-name: User Login
      parameters:
      - name: ain
        in: query
        required: true
        example: 4700000
        description: instituiion id
        schema:
          type: string
      - name: source
        in: query
        required: true
        example: API
        description: SOURCE TYPE i.e API , TAB etc ..
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /Externalboarding/secure/newmid:
    post:
      tags:
      - Boarding
      summary: New Merchant
      description: New Merchant
      operationId: submitapplication
      x-group-name: Boarding
      x-proxy-name: Submit Application
      requestBody:
        content:
          application/json:
            schema:
              type: string
              description: encrypted string
              example: "sdsd"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                description: encrypted string
                example: ""
  /Externalboarding/secure/refmid/{appType}/{referenceMID}:
    get:
      tags:
      - Boarding
      summary: Inquiry MID
      description: Inquiry MID
      operationId: refForAdditionalMID
      x-group-name: Boarding
      x-proxy-name: Ref For Additional MID
      parameters:
      - name: appType
        in: path
        required: true
        description: ADDLTID / ADDLMID
        schema:
          type: string
          example: ADDLTID
      - name: referenceMID
        in: path
        required: true
        description: mid
        schema:
          type: string
          example: 99000154
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                 $ref: '#/components/schemas/Response'
  /Externalboarding/secure/create:
    post:
      tags:
      - Boarding
      summary: Create Application
      description: Create Application
      operationId: createapplication
      x-group-name: Boarding
      x-proxy-name: Create Application
      requestBody:
        content:
          application/json:
            schema:
              type: string
              description: encrypted string
              example: ""
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                description: encrypted string
                example: ""
  /Externalboarding/secure/appstatus/{appUrn}:
    get:
      tags:
      - Boarding
      summary: Application Status
      description: Application Status
      operationId: getAppStatus
      x-group-name: Boarding
      x-proxy-name: Get App Status
      parameters:
      - name: appUrn
        in: path
        description: Application - Unique Identification number 
        required: true
        schema:
          type: string
          example: "1000007294"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
  /Externalboarding/secure/packages:
    get:
      tags:
      - Boarding
      summary: Get Package List
      description: Get Package List
      operationId: getPackageList
      x-group-name: Boarding
      x-proxy-name: Get Package List
      parameters:
      - name: RequestParam
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/DocAndPkgRequestParam'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PkgListResponse'

  /Externalboarding/secure/msf/{msfId}:
    get:
      tags:
      - Boarding
      summary: MSF Tariff 
      description: Get MSFProfile Details
      operationId: getMsById
      x-group-name: Boarding
      x-proxy-name: MSF Tariff Inquiry
      parameters:
      - name: msfId
        in: path
        required: true
        description: msf id
        schema:
          type: string
          example: 745
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /Externalboarding/secure/addtid:
    post:
      tags:
      - Boarding
      summary: Additional Device
      description: Additional Terminal
      operationId: submitAdditionalTidApplication
      x-group-name: Boarding
      x-proxy-name: Additional Device
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /Externalboarding/secure/document:
    get:
      tags:
      - Boarding
      summary: document Matrix 
      description: Get Document List
      operationId: getDocumentList
      x-group-name: Boarding
      x-proxy-name: Get Document List
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocAndPkgRequestParam'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string

  /Externalboarding/secure/addmid:
    post:
      tags:
      - Boarding
      summary: Additional Outlet
      description: Additional Merchant
      operationId: submitAdditionalMidApplication
      x-group-name: Boarding
      x-proxy-name: Additional Outlet
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  
  /Externalboarding/secure/document/{appUrn}:
    post:
      tags:
      - Boarding
      summary: Document Upload
      description: Document Upload
      operationId: uploadMerchantDocument
      x-group-name: Boarding
      x-proxy-name: Document Upload
      parameters:
      - name: appUrn
        in: path
        required: true
        schema:
          type: string
          description: App URN
          example: 1000004745
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MerchantDocumentUploadRequest'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /secure/packages/{packageId}:
    get:
      tags:
      - Boarding
      summary: Get Package Info
      operationId: getPackageById
      x-group-name: Boarding
      x-proxy-name: Get Individual Package
      parameters:
      - name: packageId
        in: path
        description: package id
        required: true
        schema:
          type: string
          example: 7502
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    PkgListResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
        data:
          type: object
        documentOverride:
          type: array
          items:
            $ref: '#/components/schemas/DocumentOverride'
    MerchantDocumentUploadRequest:
      type: object
      properties:
        docType:
          type: string
          example: Cheque
          description: document type
        fileType:
          type: string
          example: .jpeg
          description: filet Type
        principalNo:
          type: string
          example: "1"
          description: Principal No
        categoryName:
          type: string
          example: "Fungding proof"
          description: category name
        level:
          type: string
          example: "1"
        entity:
          type: string
          example: "Merchant"
        Mandatory:
          type: string 
          example: "Y"
        imageback:
            type: string
            format: binary
        imageFront:
            type: string
            format: binary
    DocumentOverride:
      type: object
      properties:
        packageId:
          type: string
        category:
          type: string
        documentId:
          type: string
    DocAndPkgRequestParam:
      type: object
      properties:
        appType:
          type: string
          description: Application type
          example: API
        mccCode:
          type: string
          description: Merchant currency code
          example: 5813
        merchantType:
          type: string
          description: Merchant Type
          example: SM
        acceptanceType:
          type: string
          description: Acceptance Type
          example: POSMOB
        typeOfBusiness:
          type: string
          description: type of business
          example: SOLPROR
        international:
          type: string
          description: international
          example: No
        iciciMerchant:
          type: string
          description: ICICI Merchant
          example: No
        dcc:
          type: string
          description: Dynamic currency code
          example: Yes
        fundingCurrency:
          type: string
          description: Funding Currency
          example: NET_AUD
        boardingType:
          type: string
          description: Boarding Type
          example: NEWMID
        merchantGrade:
          type: string
          description: Merchant Grade
          example: NA
        newFundingAc:
          type: string
          description: new funding account
          example: ""
    Response:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status"
        data:
          type: object
    Status:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type: string

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
